"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"

interface ImportPreview {
  importSourceId: string
  importSourceName: string
  schemaVersion: string
  generatedAt: Date
  totalResources: number
  summary: {
    new: number
    changed: number
    unchanged: number
    missing: number
    conflicts: number
  }
  matches: MatchResult[]
  collectorWarnings: any[]
  canImport: boolean
  errors?: string[]
}

interface MatchResult {
  externalId: string
  name: string
  matchType: "existing_mapping" | "new" | "changed" | "unchanged" | "missing" | "conflict"
  existingSystemId?: string | null
  existingSystem?: {
    id: string
    name: string
    type: string
    status: string
  } | null
  proposedChanges?: Record<string, { old: any; new: any }>
  conflictCandidates?: Array<{
    id: string
    name: string
    type: string
    reason: string
  }>
  warnings?: string[]
}

interface ConflictResolution {
  externalId: string
  action: "match_existing" | "create_new" | "skip"
  systemId?: string
}

interface ProxmoxImportFormProps {
  locations: Array<{ id: string; name: string }>
}

export function ProxmoxImportForm({ locations }: ProxmoxImportFormProps) {
  const router = useRouter()
  const [step, setStep] = useState<"upload" | "preview" | "confirm" | "results">("upload")
  const [file, setFile] = useState<File | null>(null)
  const [locationId, setLocationId] = useState("")
  const [preview, setPreview] = useState<ImportPreview | null>(null)
  const [conflictResolutions, setConflictResolutions] = useState<Map<string, ConflictResolution>>(new Map())
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<any>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0]
    if (selectedFile) {
      setFile(selectedFile)
      setError(null)
    }
  }

  const handlePreview = async () => {
    if (!file) {
      setError("Please select a file")
      return
    }

    setLoading(true)
    setError(null)

    try {
      const formData = new FormData()
      formData.append("file", file)

      const response = await fetch("/api/imports/proxmox/preview", {
        method: "POST",
        body: formData,
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate preview")
      }

      if (data.errors && data.errors.length > 0) {
        setError(data.errors.join("; "))
        return
      }

      setPreview(data)
      setStep("preview")
    } catch (err: any) {
      setError(err.message || "Failed to generate preview")
    } finally {
      setLoading(false)
    }
  }

  const handleConflictResolution = (externalId: string, action: "match_existing" | "create_new" | "skip", systemId?: string) => {
    const newResolutions = new Map(conflictResolutions)
    newResolutions.set(externalId, { externalId, action, systemId })
    setConflictResolutions(newResolutions)
  }

  const handleConfirm = () => {
    if (!locationId) {
      setError("Please select a location")
      return
    }

    const unresolvedConflicts = preview?.matches.filter(
      m => m.matchType === "conflict" && !conflictResolutions.has(m.externalId)
    )

    if (unresolvedConflicts && unresolvedConflicts.length > 0) {
      setError("Please resolve all conflicts before importing")
      return
    }

    setStep("confirm")
  }

  const handleExecute = async () => {
    if (!file || !locationId) {
      setError("Missing required data")
      return
    }

    setLoading(true)
    setError(null)

    try {
      const formData = new FormData()
      formData.append("file", file)
      formData.append("locationId", locationId)
      formData.append("conflictResolutions", JSON.stringify(Array.from(conflictResolutions.values())))

      const response = await fetch("/api/imports/proxmox/execute", {
        method: "POST",
        body: formData,
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Failed to execute import")
      }

      setResult(data)
      setStep("results")
    } catch (err: any) {
      setError(err.message || "Failed to execute import")
    } finally {
      setLoading(false)
    }
  }

  if (step === "upload") {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-white">Step 1: Upload Proxmox Export</h2>
          <p className="mt-2 text-sm text-slate-400">
            Upload the JSON file generated by the Proxmox inventory collector
          </p>
        </div>

        {error && (
          <div className="rounded-lg bg-red-500/10 border border-red-500/20 p-4">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}

        <div className="rounded-lg border border-slate-800 bg-slate-900 p-6">
          <label className="block">
            <span className="text-sm font-medium text-white">Select JSON File</span>
            <input
              type="file"
              accept="application/json,.json"
              onChange={handleFileChange}
              className="mt-2 block w-full text-sm text-slate-400 file:mr-4 file:rounded file:border-0 file:bg-slate-800 file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-slate-700"
            />
          </label>

          {file && (
            <div className="mt-4 text-sm text-slate-400">
              <p>Selected: {file.name}</p>
              <p>Size: {(file.size / 1024).toFixed(2)} KB</p>
            </div>
          )}
        </div>

        <div className="flex gap-3">
          <button
            onClick={() => router.push("/dashboard/settings/imports")}
            className="rounded border border-slate-700 bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
          >
            Cancel
          </button>
          <button
            onClick={handlePreview}
            disabled={!file || loading}
            className="rounded bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? "Generating Preview..." : "Generate Preview"}
          </button>
        </div>
      </div>
    )
  }

  if (step === "preview" && preview) {
    const conflicts = preview.matches.filter(m => m.matchType === "conflict")
    const canProceed = conflicts.every(c => conflictResolutions.has(c.externalId))

    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-white">Step 2: Review Preview</h2>
          <p className="mt-2 text-sm text-slate-400">
            Review the changes that will be made during import
          </p>
        </div>

        {error && (
          <div className="rounded-lg bg-red-500/10 border border-red-500/20 p-4">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
          <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
            <div className="text-2xl font-bold text-green-400">{preview.summary.new}</div>
            <div className="text-sm text-slate-400">New</div>
          </div>
          <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
            <div className="text-2xl font-bold text-blue-400">{preview.summary.changed}</div>
            <div className="text-sm text-slate-400">Changed</div>
          </div>
          <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
            <div className="text-2xl font-bold text-slate-400">{preview.summary.unchanged}</div>
            <div className="text-sm text-slate-400">Unchanged</div>
          </div>
          <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
            <div className="text-2xl font-bold text-yellow-400">{preview.summary.conflicts}</div>
            <div className="text-sm text-slate-400">Conflicts</div>
          </div>
          <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
            <div className="text-2xl font-bold text-orange-400">{preview.summary.missing}</div>
            <div className="text-sm text-slate-400">Missing</div>
          </div>
        </div>

        <div className="rounded-lg border border-slate-800 bg-slate-900 p-6">
          <label className="block">
            <span className="text-sm font-medium text-white">Target Location *</span>
            <select
              value={locationId}
              onChange={(e) => setLocationId(e.target.value)}
              className="mt-2 block w-full rounded border border-slate-700 bg-slate-800 px-3 py-2 text-white focus:border-blue-500 focus:outline-none"
            >
              <option value="">Select location for new systems...</option>
              {locations.map((loc) => (
                <option key={loc.id} value={loc.id}>
                  {loc.name}
                </option>
              ))}
            </select>
          </label>
        </div>

        {conflicts.length > 0 && (
          <div className="rounded-lg border border-yellow-500/20 bg-yellow-500/10 p-6">
            <h3 className="text-lg font-semibold text-yellow-400">Resolve Conflicts</h3>
            <p className="mt-2 text-sm text-slate-400">
              The following resources require manual resolution:
            </p>
            <div className="mt-4 space-y-4">
              {conflicts.map((match) => (
                <div key={match.externalId} className="rounded border border-slate-700 bg-slate-900 p-4">
                  <div className="font-medium text-white">{match.name}</div>
                  <div className="mt-1 text-sm text-slate-400">{match.externalId}</div>
                  {match.warnings && match.warnings.length > 0 && (
                    <div className="mt-2 text-sm text-yellow-400">{match.warnings[0]}</div>
                  )}
                  <div className="mt-4 space-y-2">
                    <label className="flex items-center gap-2">
                      <input
                        type="radio"
                        name={`conflict-${match.externalId}`}
                        checked={conflictResolutions.get(match.externalId)?.action === "create_new"}
                        onChange={() => handleConflictResolution(match.externalId, "create_new")}
                        className="text-blue-600"
                      />
                      <span className="text-sm text-white">Import as new system</span>
                    </label>
                    <label className="flex items-center gap-2">
                      <input
                        type="radio"
                        name={`conflict-${match.externalId}`}
                        checked={conflictResolutions.get(match.externalId)?.action === "skip"}
                        onChange={() => handleConflictResolution(match.externalId, "skip")}
                        className="text-blue-600"
                      />
                      <span className="text-sm text-white">Skip this resource</span>
                    </label>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="flex gap-3">
          <button
            onClick={() => setStep("upload")}
            className="rounded border border-slate-700 bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
          >
            Back
          </button>
          <button
            onClick={handleConfirm}
            disabled={!canProceed || !locationId}
            className="rounded bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Continue to Confirmation
          </button>
        </div>
      </div>
    )
  }

  if (step === "confirm" && preview) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-white">Step 3: Confirm Import</h2>
          <p className="mt-2 text-sm text-slate-400">
            Review and confirm the import operation
          </p>
        </div>

        {error && (
          <div className="rounded-lg bg-red-500/10 border border-red-500/20 p-4">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}

        <div className="rounded-lg border border-blue-500/20 bg-blue-500/10 p-6">
          <h3 className="text-lg font-semibold text-blue-400">Import Summary</h3>
          <dl className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between">
              <dt className="text-slate-400">Source:</dt>
              <dd className="text-white">{preview.importSourceName}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-slate-400">Total Resources:</dt>
              <dd className="text-white">{preview.totalResources}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-slate-400">New Systems:</dt>
              <dd className="text-green-400">{preview.summary.new}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-slate-400">Updated Systems:</dt>
              <dd className="text-blue-400">{preview.summary.changed}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-slate-400">Unchanged Systems:</dt>
              <dd className="text-slate-400">{preview.summary.unchanged}</dd>
            </div>
          </dl>
        </div>

        <div className="rounded-lg border border-yellow-500/20 bg-yellow-500/10 p-6">
          <h3 className="text-lg font-semibold text-yellow-400">Important</h3>
          <ul className="mt-2 space-y-1 text-sm text-slate-300 list-disc list-inside">
            <li>This operation will modify your inventory database</li>
            <li>Changes cannot be automatically undone</li>
            <li>Manually maintained fields will be preserved</li>
            <li>Missing resources will not be automatically deleted</li>
          </ul>
        </div>

        <div className="flex gap-3">
          <button
            onClick={() => setStep("preview")}
            className="rounded border border-slate-700 bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
          >
            Back
          </button>
          <button
            onClick={handleExecute}
            disabled={loading}
            className="rounded bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? "Importing..." : "Confirm and Import"}
          </button>
        </div>
      </div>
    )
  }

  if (step === "results" && result) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-white">Import Complete</h2>
          <p className="mt-2 text-sm text-slate-400">
            The import has been completed successfully
          </p>
        </div>

        <div className={`rounded-lg border p-6 ${
          result.status === "COMPLETED" 
            ? "border-green-500/20 bg-green-500/10" 
            : "border-yellow-500/20 bg-yellow-500/10"
        }`}>
          <h3 className={`text-lg font-semibold ${
            result.status === "COMPLETED" ? "text-green-400" : "text-yellow-400"
          }`}>
            {result.status === "COMPLETED" ? "Success" : "Completed with Warnings"}
          </h3>
          <dl className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between">
              <dt className="text-slate-400">New Systems Created:</dt>
              <dd className="text-green-400">{result.newCount}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-slate-400">Systems Updated:</dt>
              <dd className="text-blue-400">{result.updatedCount}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-slate-400">Systems Unchanged:</dt>
              <dd className="text-slate-400">{result.unchangedCount}</dd>
            </div>
            {result.conflictCount > 0 && (
              <div className="flex justify-between">
                <dt className="text-slate-400">Conflicts Skipped:</dt>
                <dd className="text-yellow-400">{result.conflictCount}</dd>
              </div>
            )}
          </dl>
        </div>

        <div className="flex gap-3">
          <button
            onClick={() => router.push("/dashboard/systems")}
            className="rounded bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            View Systems
          </button>
          <button
            onClick={() => router.push("/dashboard/settings/imports")}
            className="rounded border border-slate-700 bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
          >
            View Import History
          </button>
        </div>
      </div>
    )
  }

  return null
}
